/*
  ____                                   _             _
 / ___|  ___  _   _ _ __ ___ ___   _ __ | |_   _  __ _(_)_ __
 \___ \ / _ \| | | | '__/ __/ _ \ | '_ \| | | | |/ _` | | '_ \
  ___) | (_) | |_| | | | (_|  __/ | |_) | | |_| | (_| | | | | |
 |____/ \___/ \__,_|_|  \___\___| | .__/|_|\__,_|\__, |_|_| |_|
                                  |_|            |___/
# A Template for ArduinoPlugin, a Source Plugin
# Generated by the command: plugin -t source -d arduino_plugin arduino
# Hostname: Fram-IV.local
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2024-07-31T08:52:13.115+0200
# NOTICE: MADS Version 1.0.0
*/
// Mandatory included headers
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <source.hpp>
// other includes as needed here
#include <chrono>
#include <thread>
#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

#include <serialport.hpp>

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "arduino_dashboard"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class ArduinoDashboardPlugin : public Source<json> {

public:
  string kind() override { return PLUGIN_NAME; }

  return_type get_output(json &out,
                         vector<unsigned char> *blob = nullptr) override {
    if (_setup_error) {
      return return_type::critical;
    }
    string line;
    json data;
    bool success = false;
    out.clear();

    do {
      line.clear();
      _serialPort->read_line(line);
      try {
        data = json::parse(line);
        success = true;
      } catch (json::exception &e) {
        _error = e.what();
        return return_type::error;
      }
    } while (success == false);

    out["event"] = data["data"]["event"];
    out["info"]["flag"] = data["data"]["flag"];
    out["info"]["count"] = data["count"];
    out["info"]["millis"] = data["millis"];
    if (data["data"]["event"] == "logging On") {
      out["pause"] = false;
    } else if (data["data"]["event"] == "logging Off") {
      out["pause"] = true;
    }

    if (!_agent_id.empty())
      out["agent_id"] = _agent_id;
    return return_type::success;
  }

  void set_params(const json &params) override {
    Source::set_params(params);
    _params["port"] = "/dev/ttyUSB0";
    _params["baudrate"] = 115200;
    _params["silent"] = true;
    _params["connection_timeout"] = 5000u;
    _params["cfg_cmd"] = "";
    _params.merge_patch(params);

    auto ports = SerialPort::available_ports();
    if (std::find(ports.begin(), ports.end(), _params["port"].get<string>()) ==
        ports.end()) {
      _error = "Port does not exist";
      _setup_error = true;
      return;
    }

    auto config = SerialPort::Config{};
    config.baud_rate = _params["baudrate"].get<unsigned>();
    config.timeout =
        chrono::milliseconds(_params["connection_timeout"].get<unsigned>());

    try {
      _serialPort =
          make_unique<SerialPort>(_params["port"].get<string>(), config);
    } catch (std::exception &e) {
      _error = e.what();
      _setup_error = true;
      return;
    }

    if (_params.find("cfg_cmd") != _params.end() &&
        !_params["cfg_cmd"].empty()) {
      _serialPort->write(_params["cfg_cmd"].get<string>().c_str());
      _serialPort->write("\n");
    }
  }

  map<string, string> info() override {
    return {{"port", _params["port"].get<string>()},
            {"baudrate", to_string(_params["baudrate"].get<unsigned>())},
            {"cfg_cmd", _params["cfg_cmd"].get<string>()},
            {"connection_timeout",
             to_string(_params["connection_timeout"].get<unsigned>())}};
  };

private:
  bool _setup_error = false;
  json _data, _params;
  unique_ptr<SerialPort> _serialPort;
  array<bool, 4> _channels = {false, false, false, false};
};

/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
MADS_REGISTER_PLUGINS(ArduinoDashboardPlugin)

/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/

#include <csignal>

static bool running = true;

int main(int argc, char const *argv[]) {
  ArduinoDashboardPlugin plugin;
  json output;
  unsigned long i = 0;

  if (argc < 2) {
    cout << "Usage: " << argv[0] << " <port> | -e" << endl;
    return 1;
  }

  if (string(argv[1]) == "-e") {
    auto ports = SerialPort::available_ports();
    for (const auto &port : ports) {
      cout << port << endl;
    }
    return 0;
  }

  signal(SIGINT, [](int) { running = false; });

  // Set parameters
  json params;
  params["port"] = argv[1];
  params["baudrate"] = 115200;
  params["silent"] = false;
  params["cfg_cmd"] = "500p";
  plugin.set_params(params);

  while (running) {
    plugin.get_output(output);
    cout << "message #" << setfill('0') << setw(6) << i++ << ": "
         << output.dump() << endl;
  }

  return 0;
}
